all: sw10_pcmconvert.exe

ifeq (x$(CC)y$(MSYSTEM)z, xccyCLANG64z)
CC = clang
else ifeq (x$(CC)y$(MSYSTEM)z, xccyCLANGARM64z)
CC = clang
else ifeq ($(CC), cc)
CC = gcc
endif

sw10_pcmconvert.exe: sw10_pcmtools.c midi_loader.c midi_loader.h ../VLSG/VLSG.c ../VLSG/VLSG.h
	$(CC) -O2 -Wall -DPCM_TOOL=PCM_CONVERT_INTERNAL -o sw10_pcmconvert.exe sw10_pcmtools.c midi_loader.c ../VLSG/VLSG.c -I../VLSG

.PHONY: clean
clean:
ifdef MSYSTEM
	rm -f sw10_pcmconvert.exe
else
	del sw10_pcmconvert.exe
endif
